name: run service.py

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .gen_epg
    tags-ignore:
      - "*"
  schedule:
    - cron: "0 0 */5 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install bs4
          pip install requests
      - name: execute py script # run service.py
        run: python -c "import os; os.chdir('.epg'); import c"     
      - name: commit files
        run: |
          git config --local user.email "eyMarv07@gmail.com"
          git config --local user.name "eyMarv"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated epg" --allow-empty)   
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
